apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  # No quote filter; keep```yaml
      targetPort: 5001
  type: {{ .Values.service.type | quote }}
